# This is a basic workflow to help you get started with Actions

name: Selfhosted runner workflow on SAS9.4

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on - test changes to see if it works
    runs-on: [self-hosted, race]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a single line just to test
      - shell: cmd
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
      - shell: cmd
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
